### ISSUE TITLE
User Management required?

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/NotificationProxy#23]
### Wie sieht die Authentifizierung aus? Brauchen wir ein User- und Rechtesystem?
Again, I'm not sure I understand the question correctly, since it seems to be already answered in the OAS.
Services (e.g. /v1/notify-device-attribute-value-changes) are protected by operation keys and OAM paths (e.g. /core-model-1-4:control-construct/profile-collection/profile={uuid}) are protected by basic auth.
Both should already be provided by the ApplicationPattern and the TinyApplicationController.

**Comment by FelixFleckensteinMentopolis** [comment]
We read into the topic and understood the mechanism for authentication.
