### ISSUE TITLE
Logic in Individual Services Required

### ISSUE THREAD

**Issue by FelixFleckensteinMentopolis** [openBackhaul/NotificationProxy#24]
**Gibt es Logik in den einzelnen Individual-Services (z.B. Zusammenfassen der Alarme oder Umrechnung in ein einheitliches Format), oder werden die Notifications 1:1 durchgereicht?**

Yes, there is logic to be implemented.
E.g. duplicate notifications have to be suppressed and object references have to be translated.

**What about the "counter" field. Is this the 1:1 counter value from device-notifications, or should we implement an own counter?**

**Comment by openBackhaul** [comment]
> What about the "counter" field. Is this the 1:1 counter value from device-notifications, or should we implement an own counter?  

In case of _device notifications_, the counter received from the device has to be copied into the outgoing notification.  

In case of _controller notifications_, the NP has to implement an own counter for every callback (individual type of notifications that is available for separate subscription).

**Comment by openBackhaul** [comment]
Whenever all questions could be clarified, please close the issue.
