### ISSUE TITLE
additionalProperties:false property to be added for the action-profile schema of core-model-1-4:control-construct

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NotificationProxy#25]
In ApplicationPattern , we have an open issue https://github.com/openBackhaul/ApplicationPattern/issues/578.
This issue also needs to be solved in RequestSequenceRepresentation.

Note : As of now , in the server side generated yaml file , manually we included additionalProperties:false(as described in this https://github.com/openBackhaul/ApplicationPattern/issues/578) to resolve this problem.

(Also see [ALAP] issue https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/107)

**Comment by PrathibaJee** [comment]
For now , in server side code , in the api/openapi.yaml file , additionalProperties:false needs to be included as mentioned in the below two lines

![image](https://github.com/openBackhaul/NotificationProxy/assets/62344562/3f0530c6-0b2b-4da6-968e-25e27afbfd7f)

![image](https://github.com/openBackhaul/NotificationProxy/assets/62344562/26d029de-2308-4332-89a3-b21d476be65e)

**Comment by openBackhaul** [comment]
additionalProperties: false statement has been added at the action-profile-1-0:action-profile-pac definitions.
