### ISSUE TITLE
Behavior in case of controller is not responding

### ISSUE THREAD

**Issue by FelixFleckensteinMentopolis** [openBackhaul/NotificationProxy#28]
If controllers which are sending notifications to NotificationProxy become unreachable, what is the expected way to handle this? Should NotificationProxy try to reconnect to a known controller for a length of time,  should it wait for the next call to "listen-to-controllers" for reestablishing the connection or should the controller be removed?

**Comment by openBackhaul** [comment]
Currently the SDN controllers are represented as individual instances of ODL.
This lead to some confusion as multiple instances have been put into parallel operation.
Negative impact on MWDI and potentially other applications has been realized.

The representation of the SDN controller shall undergo a redesign that shall lead to a single logical controller.
Individual applications shall not need to deal with unavailable or changing controllers.

This planned change might have some impact on NP, too, but if some change would be required, it would be a simplification.

We could leave this issues open as a reminder for potential need to adapt to the changed controller design, but there is no need for change in the current release.

**Comment by FelixFleckensteinMentopolis** [comment]
As described by Thorsten, this function is not required.
