### ISSUE TITLE
Dedicated Users on the controller for ODL notification stream and Device notification stream 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#39]
We dont have specific requirement in specification to create dedicated users.
If dedicate users will be helpful for the application then we can create dedicated users on controller. 

Proposal:
Every controller shall be configured with two dedicated users,
1. For Device notification stream Username:notifdevice
2. For ODL notification stream (config +oper) Username:notifcontroller
On the notification proxy application both these users should be configured. 
Application owner can confirm this please.

**Comment by openBackhaul** [comment]
The NP shall have two different users/passwords.
One for connecting to the load ballancer for receiving device notifications.
One for connecting to the ODL, respectively the future Controller (ControllerManager application).
