### ISSUE TITLE
Is notification proxy required to subscribe ODL notification (config+oper)

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#41]
As per current implementation, ODL subscription is taken care during the start-up of the controller instance.

Notification proxy is also subscribing to ODL notification streams whenever it is started /restarted.

So there is duplicate process of ODL subscription.

what is the expectation for ODL subscription?

**Comment by openBackhaul** [comment]
Is there some harm coming from doing it twice?  
If not, we could leave as is for the moment and formulate an issue for removing the affected one or two callbacks with the next release.
If there is some hard, we could put a silly value for the operationClient into the CONFIGfile and formulate an issue for removing the affected one or two callbacks with the next release.

**Comment by Ziabatcha** [comment]
ODL subscription will never get interrupted when we invoke subscribing request multiple times. Able to receive the notification continuously on same active session. 
Hence there is no harm when we subscribe subscription again and again
