### ISSUE TITLE
Device notification grouping differs between notification-1-0 yang and interface yang

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#42]
In Notification yang,  it specifies "leaf object-path" under all three notification types.  
Snippet shared below:
```
leaf object-path {
      type instance-identifier;
      config false;
      mandatory true;
      description
        "Path from the top level element (e.g. ControlConstruct) to the object that got created. In YANG, it would be the container or list that got created.";
    }
```

In interface yang, it specifies "leaf object-id-ref" under all three notification types.   
Snippet shared below:  
```
 leaf object-id-ref {
      type leafref {
        path "/core-model:control-construct/core-model:logical-termination-point/core-model:uuid";
        require-instance false;
      }
      config false;
      mandatory true;
      description
        "none";
    }
```
In Notification proxy, required attribute for the notification is mentioned 
https://github.com/openBackhaul/NotificationProxy/blob/develop/spec/NotificationProxy.yaml#L2419
 required:
                            - counter
                            - timestamp
                            - resource
                            - attribute-name
                            - new-value

Would resource in Notification proxy consider "object-id-ref" or "object-path" value as "resource". Please confirm.

**Comment by openBackhaul** [comment]
Notifications format updated on the ingress and on the egress.
objectPath is the correct attribute.
