### ISSUE TITLE
Observing error response when user tried to trigger device -object create notification

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#44]
After invoking API request:/v1/notify-device-object-creations, got response as 204 in swagger.
Now user tried to trigger the device attribute change notification from device, observing below error message in docker logs

Logs:
[11:20:21.004] ERROR (1): error during subscriber-notification for /v1/notify-device-object-creations
```
    err: {
      "message": "Request failed with status code 400",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 400
              at settle (/home/openbackhaul/NotificationProxy/node_modules/axios/dist/node/axios.cjs:1913:12)
              at IncomingMessage.handleStreamEnd (/home/openbackhaul/NotificationProxy/node_modules/axios/dist/node/axios.cjs:2995:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1358:12)
              at processTicksAndRejections (node:internal/process/task_queues:83:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
          "Blob": null
        },
```
```
        "method": "post",
        "url": "HTTP://x.x.x.x:xxxx/v1/regard-device-object-creation",
        "data": "{\"notification-proxy-1-0:object-creation-notification\":{\"timestamp\":\"2023-11-30T11:20:20.0+00:00\",\"counter\":9,\"resource\":\"/core-model-1-4:network-control-domain=live/control-construct=513250007/forwarding-domain[uuid='VLAN-FD']/fc[uuid='VLAN-223']\"}}"
      },
      "code": "ERR_BAD_REQUEST",
      "status": 400
    }
```

**Comment by FelixFleckensteinMentopolis** [comment]
Done.
The logic for determining the resource path has been adapted.
Please retest.

**Comment by Ziabatcha** [comment]
Still observing the issue in v1.0.0_impl branch
logs:
 "method": "post",
        "url": "HTTP://x.x.x.x:xxxx/v1/regard-device-object-creation",
        "data": "{\"notification-proxy-1-0:object-creation-notification\":{\"timestamp\":\"2023-12-07T06:10:34.0+00:00\",\"counter\":11,\"resource\":\"/core-model-1-4:network-control-domain=live/control-construct=513250007/forwarding-domain[uuid='VLAN-FD']/fc[uuid='VLAN-291']\",\"object-type\":\"\"}}"
      },
      "code": "ERR_BAD_RESPONSE",
      "status": 500
    }

**Comment by pBittenbringMentopolis** [comment]
Hello Thorsten,
 
the "object-type" field of input notifications is missing and will be empty in the output notification. The "resource" field of output may be incomplete.
 
input: 
{
    "ietf-restconf:notification": {
        "notifications-1-0:object-creation-notification": {
            "timestamp": "2023-11-29T09:31:01.0+00:00",
            "counter": 3,
            "object-path": "/core-model-1-4:control-construct/forwarding-domain[uuid='VLAN-FD']/fc[uuid='VLAN-221']"
        }
    },
    "event-time": "2023-11-29T09:31:01Z",
    "node-id": "513250007"
}
 
 
output: 
{
    "notification-proxy-1-0:object-creation-notification": {
        "timestamp": "2023-11-29T09:31:01.0+00:00",
        "counter": 3,
        "resource": "/core-model-1-4:network-control-domain=live/control-construct=513250007/forwarding-domain[uuid='VLAN-FD']/fc[uuid='VLAN-221']",
        "object-type": ""
    }
}
 
Could you verify that the output notification is as expected? If the format is correct, the error is most likely in MWDI "regard-device-object-creation" method.
