### ISSUE TITLE
Observing error when alarm notification is sent to subscriber

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#55]
When Alarm notification is received and sent to subscriber, observing error because of resource. 

As per specification, https://github.com/openBackhaul/NotificationProxy/blob/develop/spec/NotificationProxy.yaml#L3172
 example: '[/core-model-1-4:network-control-domain=live/control-construct=][{mount-name}][/logical-termination-point={uuid}/layer-protocol={local-id}/air-interface-2-0:air-interface-pac]'

Alarm notification is not aligned as per specification
"resource":"/core-model-1-4:network-control-domain=live/control-construct=NODEA/logical-termination-point[uuid='LTP-MWPS-TTP-1-1']"

**Comment by pBittenbringMentopolis** [comment]
Hello Thorsten, could you clarify the resource path structure which is needed for alarm notifications? We are currently parsing it like this:
 
Input: 
{
    "ietf-restconf:notification": {
        "alarms-1-0:alarm-event-notification": {
            "alarm-event-sequence-number": 68,
            "problem-severity": "alarms-1-0:SEVERITY_AND_CLEARED_TYPE_CRITICAL",
            "timestamp": "2023-11-21T06:27:13+01:00",
            "resource": "/core-model-1-4:control-construct/logical-termination-point[uuid='ETY-86.1.1']",
            "alarm-type-qualifier": "",
            "alarm-type-id": "alarms-ext-ericsson-ml6300:ALARM_TYPE_ID_linkDown"
        }
    }, "event-time": "2023-11-21T05:27:13.715Z", "node-id": "513559991A"
}
 
 
output: 
{
    "notification-proxy-1-0:alarm-event-notification": {
        "alarm-event-sequence-number": 68,
        "problem-severity": "alarms-1-0:SEVERITY_AND_CLEARED_TYPE_CRITICAL",
        "timestamp": "2023-11-21T06:27:13+01:00",
        "resource": "/core-model-1-4:network-control-domain=live/control-construct=513559991A/logical-termination-point[uuid='ETY-86.1.1']",
        "alarm-type-qualifier": "",
        "alarm-type-id": "alarms-ext-ericsson-ml6300:ALARM_TYPE_ID_linkDown",
    }
}
 
 
Spec says: Path to the object where the error occurred from [/core-model-1-4:network-control-domain=live/control-construct=][{$/v1/add-controller.callbacks.PromptForListenToControllersCausesSubscribingForDeviceNotifications.response.body#node-id}][path to the class derived from {$/v1/add-controller.callbacks.PromptForListenToControllersCausesSubscribingForDeviceNotifications.response.body#ietf-restconf:notification/alarms-1-0:alarm-event-notification/resource}]
 
The output-resource element seems to be incomplete. Input is controller data from live system. Could you elaborate how to structure the response resource path?

**Comment by openBackhaul** [comment]
Output in [comment](https://github.com/openBackhaul/NotificationProxy/issues/55#issuecomment-1852374007) is not correct in the resource attribute.
v1.0.1_spec shall be more precise in this aspect.
