### ISSUE TITLE
Request to update operation-key value for notify-controller-attribute-value-changes

### ISSUE THREAD

**Issue by sunil-kumar-meena** [openBackhaul/NotificationProxy#57]
**Problem Description:**
As per specification NotificationProxy+config.json "operation-name": "/v1/notify-controller-attribute-value-changes" is having     operation-key present as "n.a." under operation-server-interface-configuration  as mentioned below 

```
 {
            "uuid": "np-1-0-0-op-s-is-011",
            "ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SOURCE",
            "client-ltp": [
            ],
            "server-ltp": [
              "np-1-0-0-http-s-000"
            ],
            "layer-protocol": [
              {
                "local-id": "0",
                "layer-protocol-name": "operation-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER",
                "operation-server-interface-1-0:operation-server-interface-pac": {
                  "operation-server-interface-capability": {
                    "operation-name": "/v1/notify-controller-attribute-value-changes"
                  },
                  "operation-server-interface-configuration": {
                    "life-cycle-state": "operation-server-interface-1-0:LIFE_CYCLE_STATE_TYPE_EXPERIMENTAL",
                    "operation-key": "n.a."
                  }
                }
              }
            ]
          }
```

**Proposal :**

- Updating operation-key to the default as "Operation key not yet provided."

**Comment by MFMentopolis** [comment]
We would support this proposal. However, this is a change to the specification that can only be implemented with a later update.

**Comment by sunil-kumar-meena** [comment]
> We would support this proposal. However, this is a change to the specification that can only be implemented with a later update.

Thank You!

**Comment by openBackhaul** [comment]
In the CONFIGfile:
- Values of the operationKeys of individual services (it was not just /v1/notify-controller-attribute-value-changes) changed from "n.a." to "Operation key not yet provided.".
- Values of the operationKeys of ODL clients changed from "Operation key not yet provided." to "n.a.".

Don't understand comment above: 
_"However, this is a change to the specification that can only be implemented with a later update."_
It is a value in the CONFIGfile. 
What would be the purpose of a CONFIGfile, if changing the values would require another software release?
