### ISSUE TITLE
"subscriber-notification success" message is not received for node connection status changed to connecting

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#61]
When device is moving from connected to connecting, unable to see the "subscriber-notification success, notificationType /v1/notify-controller-attribute-value-changes, target url: HTTP://x.x.x.x:xxxx/v1/regard-controller-attribute-value-change, result status: 204"

But when device is connected back to controller, able to see the print for controller attribute  value change which send to subscriber.

**Comment by pBittenbringMentopolis** [comment]
Hello Zia,

this may be a controller-related issue.
Could you sent us logs where the entry is missing like you described? We can try to reproduce this if you have the time in a joined session. Usually if the log entry is missing, there was no notification received from controller.

**Comment by Ziabatcha** [comment]
Verified this issue and actual issue on the subscriber side. Hence closing it on NP.
