### ISSUE TITLE
Need to check the resource attribute - Alarm notification

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#73]
Notification proxy message:
{
    "notification-proxy-1-0:alarm-event-notification": {
        "alarm-event-sequence-number": 1,
        "timestamp": "2024-02-07T09:49:41.0+00:00",
        "resource": "/core-model-1-4:network-control-domain=live/control-construct=513250009/logical-termination-point=LTP-MWPS-TTP-RADIO-1A/layer-protocol=LP-MWPS-TTP-RADIO-1A/air-interface-2-0:air-interface-pac",
        "alarm-type-id": "siae-alarms-1-0:radioEquipLinkTelemetryFailAlarm",
        "alarm-type-qualifier": "",
        "problem-severity": "major"
    }
}

The 500 error is caused by an error in the resource attribute of the message.
/core-model-1-4:network-control-domain=live/control-construct=513250009/logical-termination-point=LTP-MWPS-TTP-RADIO-1A/layer-protocol=LP-MWPS-TTP-RADIO-1A/air-interface-2-0:air-interface-pac is not correct as is not present in MWDI...

The available APIs are :
•	/core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-capability
•	/core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-configuration
•	/core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-status
•	/core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-historical-performances

It seems that in the resource attribute is missing the last part of the url.

**Comment by Ziabatcha** [comment]
The resource attribute contains "/core-model-1-4:control-construct" twice.

```
"resource":"/core-model-1-4:network-control-domain=live/control-construct=CO17694/core-model-1-4:control-construct/equipment=HUAWEI-EQUIPMENT-1",

```

{"notification-proxy-1-0:alarm-event-notification":{
"alarm-event-sequence-number":1702,
"timestamp":"2024-02-14T05:53:11+00:00",
"resource":"/core-model-1-4:network-control-domain=live/control-construct=CO17694/core-model-1-4:control-construct/equipment=HUAWEI-EQUIPMENT-1",
"alarm-type-id":"alarms-1-0:ALARM_TYPE_ID_TYPE_NE_OBJ",
"alarm-type-qualifier":"DCNSIZE_OVER/13110-20/FFFFFFFFFF",
"problem-severity":"major"
}
}

**Comment by paulBMentopolis** [comment]
The output resource contained in the "notification-proxy-1-0:alarm-event-notification" is built correctly according to the specification and the data received from the controller.

@openBackhaul The current "resource" structure is missing parts at the end according to MWDI specification. Please check if there is something wrong with controller input for NotificationProxy (device alarms) or the MWDI specification, as this is not an NP issue.

Example input data from controller: 
data: {"ietf-restconf:notification":{"alarms-1-0:alarm-event-notification":{"alarm-event-sequence-number":21,"problem-severity":"alarms-1-0:SEVERITY_AND_CLEARED_TYPE_CLEARED","timestamp":"2024-02-14T10:49:19.0+00:00","resource":"/core-model-1-4:control-construct/logical-termination-point[uuid='LTP-MWPS-TTP-RADIO-1A']/layer-protocol[local-id='LP-MWPS-TTP-RADIO-1A']/air-interface-2-0:air-interface-pac","alarm-type-qualifier":"","alarm-type-id":"siae-alarms-1-0:radioBranchTxPowerAlarm"}},"event-time":"2024-02-14T10:49:21Z","node-id":"513250009"}

**Comment by Ziabatcha** [comment]
As per the discussion, this issue will be fixed by MWDI team
